### ISSUE TITLE
Unable to install following install commands

### ISSUE THREAD

**Issue by rangi513** [nfultz/grpc#18]
I am trying to install this package for use on mac osx (so I'm skipping over the `sudo ldconfig` commands because I believe that is only for linux), however I seem to get an error when I get to the `./autogen.sh` command with installing gmock. 
It looks like these links have been updated in a more recent version of grpc here in this issue: https://github.com/grpc/grpc/issues/7952
with this pull request/commit: https://github.com/google/protobuf/commit/bba446bbf2ac7b0b9923d4eb07d5acd0665a8cf0 

I was able to successfully install grpc and run the `./autogen.sh` command using a the most recent release branch following instructions here https://github.com/grpc/grpc/blob/master/INSTALL.md however, if I continue with the commands in the install file for this package I get an error at this point `R CMD INSTALL grpc`.
`Warning: invalid package ‘grpc’
Error: ERROR: no packages specified`
Is the R grpc package only installable via a particular grpc branch or am I missing something simple here?

**Comment by daroczig** [comment]
I'd suggest checking the `Dockerfile`s at https://github.com/nfultz/grpc/tree/master/inst

**Comment by rangi513** [comment]
These dockerfiles are helpful for when I productionalize the code using a docker container, however I'm currently trying to develop code on a Mac. Are there equivalent instructions using something like brew for OSX?

**Comment by nfultz** [comment]
I haven't ever tried running this on a Mac, if you get it working please let us know how. Can you try running the C++ examples to rule out a problem on the R side?

One other thing to try is building the package first, then installing as a second step:

```
R CMD build grpc/
R -e "install.packages(dir(pattern = 'grpc.*.tar.gz'), repos=NULL)"
```

**Comment by long-jian** [comment]
I am trying on VM of ubuntu to install rgrpc. When I run `./autogen.sh` then same problem of this https://github.com/grpc/grpc/issues/7952.

**Comment by rangi513** [comment]
After some more digging this seemed to work for Mac
brew install --with-plugins grpc
R -e "devtools::install_github('nfultz/grpc')"
