### ISSUE TITLE
Unable to build Docker image

### ISSUE THREAD

**Issue by andrexus** [nfultz/grpc#23]
I'm trying to build a docker image from inst/docker_stable/Dockerfile but the build crashes with the following error:

```
E: Unable to locate package libgrpc3
```
After updating the package version from libgrpc3 to libgrpc6 the build is still failing with an error:

```
Error: package or namespace load failed for ‘docopt’:
 package ‘stringi’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
The command '/bin/sh -c install2.r -r https://cran.rstudio.com/ processx remotes' returned a non-zero code: 1
```

**Comment by daroczig** [comment]
yeah, apt packages in debian testing were updated recently ... I can fix this later today

**Comment by daroczig** [comment]
Please test https://github.com/nfultz/grpc/pull/24

**Comment by andrexus** [comment]
Works flawlessly!
