### ISSUE TITLE
Possible bug in helloserver/client

### ISSUE THREAD

**Issue by ghuoul** [nfultz/grpc#33]
Filling this possible issue mostly just for possible confirmation that it is not just me who is experiencing the issue

```
message of type 'helloworld.GreetingReply' with one field set

$message

[1] "Hello, Neal"

Error in client$SayThanks$callWithMetadata(thanks, c("key1", "val1")) :

attempt to apply non-function

```
Any other possibly relevant information would be much appreciated.

Cheers!

**Comment by Shehab7osny** [comment]
This issue can be solved by just replacing the function name called.
Pull request #26 initially enabled metadata to be passed as an argument in the function call().
The name of the function in the beginning was `callWithMetadata()`. However, it was later changed to just `call()` but it looks like it was not yet edited in this example, but as you can see it can be easily fixed. Hope that you can now run the example smoothly!
